var clearTimeout;
var encodeURIComponent;
var decodeURIComponent;
Window.prototype.document;
Window.prototype.requestAnimationFrame;
Window.prototype.webkitRequestAnimationFrame;
Window.prototype.mozRequestAnimationFrame;
Window.prototype.msRequestAnimationFrame;
Object.defaultValue;
Object.onChange;
Object.useState;
Object.memo;
Object.charCodeAt;
Object.Fragment;
Object.ref;
Object.ref.hasOwnProperty;
Object.ref.current;
Object.useRef;
Object.value;
Object.findDOMNode;
Object.Component;
Object.Component.call;
Object.Children;
Object.Children.toArray;
Object.useEffect;
Object.render;
Object.out;
Object.out.println;
Object.createElement;
Object.createElement.apply;
Object.unmountComponentAtNode;
Object.error;
Object.error.println;
Object.hasOwnProperty;
HTMLDocument.prototype.getElementById;
HTMLDocument.prototype.activeElement;
var process;
process.hrtime;
Uint8Array.prototype.set;
window.location;
window.location.hostname;
window.location.port;
var setTimeout;
var React;
React.Component;
React.Component.prototype.forceUpdate;
React.Component.prototype.cljsIsDirty;
React.Component.prototype.constructor$;
React.Component.prototype.props;
React.Component.prototype.props.argv;
React.Component.prototype.props.children;
var Java;
Java.type;
var unescape;
